
import React, { useState } from 'react';
import type { SimulationParams, BucketData } from '../types';
import { OtherBucket } from '../types';
import PlayIcon from './icons/PlayIcon';
import ChevronIcon from './icons/ChevronIcon';
import PlusIcon from './icons/PlusIcon';
import InfoIcon from './icons/InfoIcon';
import InputField from './InputField';
import BucketInput from './BucketInput';
import { formatCurrency } from '../services/formatters';
import { STRESS_SCENARIO_OPTIONS } from '../services/scenarios';

interface PortfolioInputFormProps {
  params: SimulationParams;
  setParams: React.Dispatch<React.SetStateAction<SimulationParams>>;
  excludeIlliquidFromBenchmark: boolean;
  setExcludeIlliquidFromBenchmark: (val: boolean) => void;
  isLoading: boolean;
  progress: number;
  totalInitialValue: number;
  isAutoRunEnabled: boolean;
  setIsAutoRunEnabled: (enabled: boolean) => void;
  onRun: () => void;
}

const PortfolioInputForm: React.FC<PortfolioInputFormProps> = ({ 
    params, 
    setParams, 
    excludeIlliquidFromBenchmark,
    setExcludeIlliquidFromBenchmark,
    isLoading, 
    progress, 
    totalInitialValue,
    isAutoRunEnabled,
    setIsAutoRunEnabled,
    onRun
}) => {
  const [isAdvancedExpanded, setIsAdvancedExpanded] = useState(false);
  
  const handleGenericChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setParams(prev => ({ ...prev, [name]: parseFloat(value) }));
  };

  const handleBucketChange = (bucketId: string, updates: Partial<BucketData>) => {
    setParams(prev => ({
      ...prev,
      buckets: prev.buckets.map(b => 
        // Use the bucket's update method to create a new immutable instance (potentially of a new class)
        b.id === bucketId ? b.update(updates) : b
      )
    }));
  };
  
  const handleRemoveBucket = (bucketId: string) => {
      setParams(prev => ({
          ...prev,
          buckets: prev.buckets.filter(b => b.id !== bucketId)
      }));
  };

  const handleAddBucket = () => {
      const newId = `custom-${Date.now()}`;
      setParams(prev => ({
          ...prev,
          buckets: [
              ...prev.buckets,
              new OtherBucket({
                  id: newId,
                  name: 'New Asset',
                  type: 'Other',
                  initialValue: 0,
                  enabled: true,
                  meanReturn: 0.08,
                  stdDev: 0.15
                  // color will be auto-generated by the constructor
              })
          ]
      }));
  };
  
  const currentYear = new Date().getFullYear();
  const selectedScenario = STRESS_SCENARIO_OPTIONS.find(s => s.id === (params.stressTestScenarioId || '')) || STRESS_SCENARIO_OPTIONS[0];

  return (
    <div className="bg-slate-800/50 p-6 rounded-xl shadow-2xl border border-slate-700 space-y-6">
      <div className="space-y-4 p-4 border border-slate-700 rounded-lg bg-slate-800">
        <h3 className="font-semibold text-cyan-400">General Settings</h3>
        <InputField 
            id="years"
            label="Investment Horizon (Years)"
            value={params.years}
            onChange={handleGenericChange}
            type="range"
            min={1}
            max={50}
            step={1}
            tooltip="How many years you plan to keep your portfolio invested."
            disabled={isLoading}
            format={(value) => `${value} (${currentYear + value})`}
        />
        <InputField 
            id="simulations"
            label="Number of Simulations"
            value={params.simulations}
            onChange={handleGenericChange}
            type="range"
            min={100}
            max={10000}
            step={100}
            tooltip="The number of different future scenarios to simulate. More simulations provide a more accurate range of outcomes."
            disabled={isLoading}
        />
        
        {!isAutoRunEnabled && (
            <button
                onClick={onRun}
                disabled={isLoading}
                className="w-full py-3 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white rounded-lg font-bold shadow-lg transition-all duration-200 flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed mt-6 mb-2"
            >
                {isLoading ? (
                    <span className="flex items-center">
                        <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        Running...
                    </span>
                ) : (
                    <>
                        <PlayIcon />
                        Run Simulation
                    </>
                )}
            </button>
        )}

        {/* Advanced Settings */}
        <div className="pt-2">
            <button
                type="button"
                className="flex items-center text-xs text-slate-400 hover:text-cyan-400 transition-colors focus:outline-none"
                onClick={() => setIsAdvancedExpanded(!isAdvancedExpanded)}
            >
                <ChevronIcon isExpanded={isAdvancedExpanded} />
                <span className="ml-1 font-medium">Advanced Settings</span>
            </button>
             <div className={`space-y-4 overflow-hidden transition-all duration-300 ease-in-out ${isAdvancedExpanded ? 'max-h-[800px] opacity-100 mt-4' : 'max-h-0 opacity-0'}`}>
                
                <InputField 
                    id="inflationRate"
                    label="Assumed Inflation Rate"
                    value={params.inflationRate}
                    onChange={handleGenericChange}
                    type="range"
                    min={0}
                    max={0.15}
                    step={0.001}
                    isPercentage
                    tooltip="The annual rate at which you expect purchasing power to decrease. Used when toggling 'Real Value' in results."
                    disabled={isLoading}
                    quickOptions={[
                        { label: '3% (Gov Target)', value: 0.03 },
                        { label: '7% (M2 Growth)', value: 0.07 }
                    ]}
                />
                <InputField 
                    id="withdrawalReturn"
                    label="Expected Withdrawal Phase Return"
                    value={params.withdrawalReturn}
                    onChange={handleGenericChange}
                    type="range"
                    min={0}
                    max={0.30}
                    step={0.001}
                    isPercentage
                    tooltip="The assumed annual investment return during your withdrawal phase (retirement). Affects the 'Perpetual Annuity' calculation in the analysis."
                    disabled={isLoading}
                    quickOptions={[
                        { label: '10% (Conservative)', value: 0.10 },
                        { label: '14% (S&P Avg)', value: 0.14 }
                    ]}
                />

                {/* Dynamic Regime Toggle */}
                <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-700/80">
                    <div className="flex items-start justify-between">
                        <div>
                            <label className="text-sm font-semibold text-slate-200 flex items-center">
                                Market Physics Engine
                                <span className="ml-2 group relative">
                                    <InfoIcon />
                                    <span className="absolute bottom-full mb-2 w-64 bg-slate-700 text-white text-xs rounded py-2 px-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300 left-1/2 -translate-x-1/2 z-20 pointer-events-none font-normal shadow-xl border border-slate-600">
                                        <strong>Standard:</strong> Gaussian random walks. Smooth, independent returns.<br/><br/>
                                        <strong>Dynamic:</strong> Includes "Regime Switching" logic. Simulates clustered volatility, correlations converging during crashes, and fat-tail events.
                                    </span>
                                </span>
                            </label>
                            <p className="text-xs text-slate-400 mt-1">
                                {params.isDynamicMode 
                                    ? "Simulating crashes, correlations, and chaos." 
                                    : "Simulating standard, idealized markets."}
                            </p>
                        </div>
                        <button
                            onClick={() => setParams(p => ({...p, isDynamicMode: !p.isDynamicMode}))}
                            className={`relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2 focus:ring-offset-slate-800 ${
                                params.isDynamicMode ? 'bg-red-500' : 'bg-slate-600'
                            }`}
                        >
                            <span
                                aria-hidden="true"
                                className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${
                                    params.isDynamicMode ? 'translate-x-5' : 'translate-x-0'
                                }`}
                            />
                        </button>
                    </div>
                </div>

                {/* Stress Test Selector */}
                <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-700/80">
                    <label htmlFor="stress-scenario" className="text-sm font-semibold text-slate-200 flex items-center mb-2">
                        Stress Test Scenario (The Apocalypse)
                        <span className="ml-2 group relative">
                            <InfoIcon />
                            <span className="absolute bottom-full mb-2 w-64 bg-slate-700 text-white text-xs rounded py-2 px-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300 left-1/2 -translate-x-1/2 z-20 pointer-events-none font-normal shadow-xl border border-slate-600">
                                Overlays historical or hypothetical disaster scripts onto the start of every simulation path. Useful for checking if you survive the worst case.
                            </span>
                        </span>
                    </label>
                    <select
                        id="stress-scenario"
                        value={params.stressTestScenarioId || ''}
                        onChange={(e) => setParams(prev => ({ ...prev, stressTestScenarioId: e.target.value || null }))}
                        className="w-full bg-slate-700 text-white rounded-md p-2 focus:ring-2 focus:ring-cyan-500 focus:outline-none disabled:opacity-75"
                        disabled={isLoading}
                    >
                        {STRESS_SCENARIO_OPTIONS.map(s => (
                            <option key={s.id} value={s.id}>{s.label}</option>
                        ))}
                    </select>
                    <p className={`text-xs mt-2 ${selectedScenario.id ? 'text-orange-400' : 'text-slate-500'}`}>
                        {selectedScenario.desc}
                    </p>
                </div>
                
                <div className="pt-2 space-y-3 border-t border-slate-700/50">
                    <div className="flex items-start">
                        <input
                            id="exclude-illiquid"
                            type="checkbox"
                            checked={excludeIlliquidFromBenchmark}
                            onChange={(e) => setExcludeIlliquidFromBenchmark(e.target.checked)}
                            className="mt-1 h-4 w-4 rounded bg-slate-700 border-slate-600 text-cyan-500 focus:ring-cyan-500 cursor-pointer"
                        />
                         <div className="ml-2">
                            <label htmlFor="exclude-illiquid" className="text-sm font-medium text-slate-300 cursor-pointer hover:text-cyan-400 transition-colors flex items-center">
                                Exclude Cash & Real Estate from Benchmarks
                                <span className="ml-1.5 group relative">
                                    <InfoIcon />
                                    <span className="absolute bottom-full mb-2 w-56 bg-slate-700 text-white text-xs rounded py-1 px-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300 left-1/2 -translate-x-1/2 z-20 pointer-events-none font-normal">
                                        If enabled, the S&P 500 and Nasdaq reference lines will be calculated based solely on your investment assets (Stocks, Crypto, etc.), ignoring Cash and Real Estate holdings.
                                    </span>
                                </span>
                            </label>
                            <p className="text-xs text-slate-500 mt-0.5">Calculates market reference lines using only liquid investment capital.</p>
                         </div>
                    </div>

                    <div className="flex items-center">
                        <input
                            id="auto-run-checkbox"
                            type="checkbox"
                            checked={isAutoRunEnabled}
                            onChange={(e) => setIsAutoRunEnabled(e.target.checked)}
                            className="h-4 w-4 rounded bg-slate-700 border-slate-600 text-cyan-500 focus:ring-cyan-500 cursor-pointer"
                        />
                        <label htmlFor="auto-run-checkbox" className="ml-2 text-sm text-slate-300 cursor-pointer select-none hover:text-cyan-400 transition-colors">
                            Auto-Run Simulation
                        </label>
                    </div>
                </div>
             </div>
        </div>

      </div>
      
      {isLoading && (
        <div
          className="w-full relative flex items-center justify-center bg-slate-700/50 text-cyan-400 font-medium py-2 px-4 rounded-lg overflow-hidden text-xs border border-slate-600"
          aria-live="polite"
          aria-busy="true"
        >
          <div
            className="absolute top-0 left-0 h-full bg-cyan-900/20 transition-width duration-150 ease-linear"
            style={{ width: `${(progress / params.simulations) * 100}%` }}
          ></div>
          <span className="relative z-10 animate-pulse">
            {`Updating projections... ${Math.round((progress / params.simulations) * 100)}%`}
          </span>
        </div>
      )}

      <div className="text-sm bg-slate-800 p-3 rounded-lg flex justify-between items-center">
          <span className="text-slate-300 font-medium">Total Initial Portfolio Value</span>
          <span className="text-cyan-300 font-bold text-lg">{formatCurrency(totalInitialValue)}</span>
      </div>

      <div className="space-y-6">
        {params.buckets.map(bucket => (
            <BucketInput 
                key={bucket.id}
                bucket={bucket}
                onChange={handleBucketChange}
                onRemove={handleRemoveBucket}
                disabled={isLoading}
            />
        ))}
        
        <button
            onClick={handleAddBucket}
            disabled={isLoading}
            className="w-full py-3 border-2 border-dashed border-slate-600 rounded-lg text-slate-400 hover:text-cyan-400 hover:border-cyan-500 hover:bg-slate-800/50 transition-all duration-200 flex items-center justify-center font-medium disabled:opacity-50 disabled:cursor-not-allowed"
        >
            <PlusIcon />
            Add Asset
        </button>
      </div>
    </div>
  );
};

export default PortfolioInputForm;
